/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaccionesRouteImport } from './routes/transacciones'
import { Route as SeguridadRouteImport } from './routes/seguridad'
import { Route as ProductoRouteImport } from './routes/producto'
import { Route as PaypalRouteImport } from './routes/paypal'
import { Route as MonederoRouteImport } from './routes/monedero'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KlarnaRouteImport } from './routes/klarna'
import { Route as ExitoRouteImport } from './routes/exito'
import { Route as EditarTarjetaRouteImport } from './routes/editar-tarjeta'
import { Route as DudasRouteImport } from './routes/dudas'
import { Route as ContinuarRouteImport } from './routes/continuar'
import { Route as IndexRouteImport } from './routes/index'

const TransaccionesRoute = TransaccionesRouteImport.update({
  id: '/transacciones',
  path: '/transacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguridadRoute = SeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoRoute = ProductoRouteImport.update({
  id: '/producto',
  path: '/producto',
  getParentRoute: () => rootRouteImport,
} as any)
const PaypalRoute = PaypalRouteImport.update({
  id: '/paypal',
  path: '/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const MonederoRoute = MonederoRouteImport.update({
  id: '/monedero',
  path: '/monedero',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KlarnaRoute = KlarnaRouteImport.update({
  id: '/klarna',
  path: '/klarna',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitoRoute = ExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarTarjetaRoute = EditarTarjetaRouteImport.update({
  id: '/editar-tarjeta',
  path: '/editar-tarjeta',
  getParentRoute: () => rootRouteImport,
} as any)
const DudasRoute = DudasRouteImport.update({
  id: '/dudas',
  path: '/dudas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuarRoute = ContinuarRouteImport.update({
  id: '/continuar',
  path: '/continuar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/continuar': typeof ContinuarRoute
  '/dudas': typeof DudasRoute
  '/editar-tarjeta': typeof EditarTarjetaRoute
  '/exito': typeof ExitoRoute
  '/klarna': typeof KlarnaRoute
  '/menu': typeof MenuRoute
  '/monedero': typeof MonederoRoute
  '/paypal': typeof PaypalRoute
  '/producto': typeof ProductoRoute
  '/seguridad': typeof SeguridadRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/continuar': typeof ContinuarRoute
  '/dudas': typeof DudasRoute
  '/editar-tarjeta': typeof EditarTarjetaRoute
  '/exito': typeof ExitoRoute
  '/klarna': typeof KlarnaRoute
  '/menu': typeof MenuRoute
  '/monedero': typeof MonederoRoute
  '/paypal': typeof PaypalRoute
  '/producto': typeof ProductoRoute
  '/seguridad': typeof SeguridadRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/continuar': typeof ContinuarRoute
  '/dudas': typeof DudasRoute
  '/editar-tarjeta': typeof EditarTarjetaRoute
  '/exito': typeof ExitoRoute
  '/klarna': typeof KlarnaRoute
  '/menu': typeof MenuRoute
  '/monedero': typeof MonederoRoute
  '/paypal': typeof PaypalRoute
  '/producto': typeof ProductoRoute
  '/seguridad': typeof SeguridadRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/continuar'
    | '/dudas'
    | '/editar-tarjeta'
    | '/exito'
    | '/klarna'
    | '/menu'
    | '/monedero'
    | '/paypal'
    | '/producto'
    | '/seguridad'
    | '/transacciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/continuar'
    | '/dudas'
    | '/editar-tarjeta'
    | '/exito'
    | '/klarna'
    | '/menu'
    | '/monedero'
    | '/paypal'
    | '/producto'
    | '/seguridad'
    | '/transacciones'
  id:
    | '__root__'
    | '/'
    | '/continuar'
    | '/dudas'
    | '/editar-tarjeta'
    | '/exito'
    | '/klarna'
    | '/menu'
    | '/monedero'
    | '/paypal'
    | '/producto'
    | '/seguridad'
    | '/transacciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContinuarRoute: typeof ContinuarRoute
  DudasRoute: typeof DudasRoute
  EditarTarjetaRoute: typeof EditarTarjetaRoute
  ExitoRoute: typeof ExitoRoute
  KlarnaRoute: typeof KlarnaRoute
  MenuRoute: typeof MenuRoute
  MonederoRoute: typeof MonederoRoute
  PaypalRoute: typeof PaypalRoute
  ProductoRoute: typeof ProductoRoute
  SeguridadRoute: typeof SeguridadRoute
  TransaccionesRoute: typeof TransaccionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacciones': {
      id: '/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof TransaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto': {
      id: '/producto'
      path: '/producto'
      fullPath: '/producto'
      preLoaderRoute: typeof ProductoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paypal': {
      id: '/paypal'
      path: '/paypal'
      fullPath: '/paypal'
      preLoaderRoute: typeof PaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monedero': {
      id: '/monedero'
      path: '/monedero'
      fullPath: '/monedero'
      preLoaderRoute: typeof MonederoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klarna': {
      id: '/klarna'
      path: '/klarna'
      fullPath: '/klarna'
      preLoaderRoute: typeof KlarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exito': {
      id: '/exito'
      path: '/exito'
      fullPath: '/exito'
      preLoaderRoute: typeof ExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-tarjeta': {
      id: '/editar-tarjeta'
      path: '/editar-tarjeta'
      fullPath: '/editar-tarjeta'
      preLoaderRoute: typeof EditarTarjetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dudas': {
      id: '/dudas'
      path: '/dudas'
      fullPath: '/dudas'
      preLoaderRoute: typeof DudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continuar': {
      id: '/continuar'
      path: '/continuar'
      fullPath: '/continuar'
      preLoaderRoute: typeof ContinuarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContinuarRoute: ContinuarRoute,
  DudasRoute: DudasRoute,
  EditarTarjetaRoute: EditarTarjetaRoute,
  ExitoRoute: ExitoRoute,
  KlarnaRoute: KlarnaRoute,
  MenuRoute: MenuRoute,
  MonederoRoute: MonederoRoute,
  PaypalRoute: PaypalRoute,
  ProductoRoute: ProductoRoute,
  SeguridadRoute: SeguridadRoute,
  TransaccionesRoute: TransaccionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
